# Myanmar: 2024 Update

# Filepaths --------------------------------------------------------------------
db_dir <- file.path("~", "Dropbox", "World Bank", "Side Work", "Myanmar Economic Monitor")
git_dir <- file.path("~", "Documents", "Github", "myanmar-economic-monitor")

data_dir      <- file.path(db_dir, "data")
ntl_bm_dir    <- file.path(data_dir, "Nighttime Lights BlackMarble")
gas_flare_dir <- file.path(data_dir, "Global Gas Flaring 2023")
gadm_dir      <- file.path(data_dir, "GADM")
gdp_dir       <- file.path(data_dir, "GDP")
wdi_dir       <- file.path(data_dir, "WDI")

fig_dir <- file.path(git_dir, "reports", "figures")

# Packages ---------------------------------------------------------------------
library(dplyr)
library(readr)
library(janitor)
library(terra)
library(sf)
library(stringr)
library(readxl)
library(exactextractr)
#library(blackmarbler)
library(geodata)
library(lubridate)
#library(rgeos)
library(leaflet)
library(leaflet.extras)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(purrr)
library(stargazer)
library(furrr)
library(stringr)
#library(rhdf5)
library(raster)
library(dplyr)
library(sf)
library(lubridate)
library(WDI)
library(broom)
library(blackmarbler)
